server:
  port: 8085
  servlet:
    context-path: /api/registration-proxy

management:
  endpoints:
    enable-by-default: false
  endpoint:
    health:
      enabled: true

kafka:
  bootstrap:
    servers: localhost:9092
  batch:
    maxbytes: 5242880
  consumer:
    group: registration-request-consumer
  topic:
    name: registration-request-topic

